const {crimsonDark, crimson, mauveDark, mauve} = require(`@radix-ui/colors`)

module.exports = {
  content: [`./src/**/*.{js,ts,jsx,tsx}`],
  mode: `jit`,
  important: true,
  theme: {
    colors: {
      crimson: {
        1: crimsonDark.crimson1,
        2: crimsonDark.crimson2,
        3: crimsonDark.crimson3,
        4: crimsonDark.crimson4,
        5: crimsonDark.crimson5,
        6: crimsonDark.crimson6,
        7: crimsonDark.crimson7,
        8: crimsonDark.crimson8,
        9: crimsonDark.crimson9,
        10: crimsonDark.crimson10,
        11: crimsonDark.crimson11,
        12: crimsonDark.crimson12,
        light: {
          1: crimson.crimson1,
          2: crimson.crimson2,
          3: crimson.crimson3,
          4: crimson.crimson4,
          5: crimson.crimson5,
          6: crimson.crimson6,
          7: crimson.crimson7,
          8: crimson.crimson8,
          9: crimson.crimson9,
          10: crimson.crimson10,
          11: crimson.crimson11,
          12: crimson.crimson12,
        },
      },
      mauve: {
        1: mauveDark.mauve1,
        2: mauveDark.mauve2,
        3: mauveDark.mauve3,
        4: mauveDark.mauve4,
        5: mauveDark.mauve5,
        6: mauveDark.mauve6,
        7: mauveDark.mauve7,
        8: mauveDark.mauve8,
        9: mauveDark.mauve9,
        10: mauveDark.mauve10,
        11: mauveDark.mauve11,
        12: mauveDark.mauve12,
        light: {
          1: mauve.mauve1,
          2: mauve.mauve2,
          3: mauve.mauve3,
          4: mauve.mauve4,
          5: mauve.mauve5,
          6: mauve.mauve6,
          7: mauve.mauve7,
          8: mauve.mauve8,
          9: mauve.mauve9,
          10: mauve.mauve10,
          11: mauve.mauve11,
          12: mauve.mauve12,
        },
      },
      transparent: `transparent`,
    },
    fontFamily: {
      sans: [`Gothic A1`, `sans-serif`],
    },
  },
}
